/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MediaRouteImport } from './routes/media'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminLearnRouteImport } from './routes/admin.learn'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminOfficesRouteImport } from './routes/admin.offices'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminRecycleRouteImport } from './routes/admin.recycle'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as DonationsIndexRouteImport } from './routes/donations.index'
import { Route as DonationsSlugRouteImport } from './routes/donations.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as OfficesIndexRouteImport } from './routes/offices.index'
import { Route as OfficesSlugRouteImport } from './routes/offices.$slug'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalManagerRouteImport } from './routes/portal.manager'
import { Route as PortalStudentRouteImport } from './routes/portal.student'
import { Route as PortalTeacherRouteImport } from './routes/portal.teacher'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PublicationsSlugRouteImport } from './routes/publications.$slug'
import { Route as ApiPublicHesabSessionRouteImport } from './routes/api/public/hesab-session'
import { Route as ApiPublicPrerenderManifestRouteImport } from './routes/api/public/prerender-manifest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearnRoute = AdminLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfficesRoute = AdminOfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecycleRoute = AdminRecycleRouteImport.update({
  id: '/recycle',
  path: '/recycle',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsIndexRoute = DonationsIndexRouteImport.update({
  id: '/donations/',
  path: '/donations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsSlugRoute = DonationsSlugRouteImport.update({
  id: '/donations/$slug',
  path: '/donations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesIndexRoute = OfficesIndexRouteImport.update({
  id: '/offices/',
  path: '/offices/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesSlugRoute = OfficesSlugRouteImport.update({
  id: '/offices/$slug',
  path: '/offices/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalManagerRoute = PortalManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStudentRoute = PortalStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTeacherRoute = PortalTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => PortalRoute,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsSlugRoute = PublicationsSlugRouteImport.update({
  id: '/publications/$slug',
  path: '/publications/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHesabSessionRoute = ApiPublicHesabSessionRouteImport.update({
  id: '/api/public/hesab-session',
  path: '/api/public/hesab-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPrerenderManifestRoute =
  ApiPublicPrerenderManifestRouteImport.update({
    id: '/api/public/prerender-manifest',
    path: '/api/public/prerender-manifest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/learn': typeof LearnRoute
  '/media': typeof MediaRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/learn': typeof AdminLearnRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/offices': typeof AdminOfficesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recycle': typeof AdminRecycleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/donations/$slug': typeof DonationsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/portal/manager': typeof PortalManagerRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/teacher': typeof PortalTeacherRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/donations/': typeof DonationsIndexRoute
  '/offices/': typeof OfficesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/hesab-session': typeof ApiPublicHesabSessionRoute
  '/api/public/prerender-manifest': typeof ApiPublicPrerenderManifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/learn': typeof LearnRoute
  '/media': typeof MediaRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/learn': typeof AdminLearnRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/offices': typeof AdminOfficesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recycle': typeof AdminRecycleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/donations/$slug': typeof DonationsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/portal/manager': typeof PortalManagerRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/teacher': typeof PortalTeacherRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/careers': typeof CareersIndexRoute
  '/donations': typeof DonationsIndexRoute
  '/offices': typeof OfficesIndexRoute
  '/portal': typeof PortalIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/public/hesab-session': typeof ApiPublicHesabSessionRoute
  '/api/public/prerender-manifest': typeof ApiPublicPrerenderManifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/learn': typeof LearnRoute
  '/media': typeof MediaRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/learn': typeof AdminLearnRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/offices': typeof AdminOfficesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recycle': typeof AdminRecycleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/donations/$slug': typeof DonationsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/portal/manager': typeof PortalManagerRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/teacher': typeof PortalTeacherRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/donations/': typeof DonationsIndexRoute
  '/offices/': typeof OfficesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/hesab-session': typeof ApiPublicHesabSessionRoute
  '/api/public/prerender-manifest': typeof ApiPublicPrerenderManifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/donate'
    | '/learn'
    | '/media'
    | '/portal'
    | '/admin/about'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/donations'
    | '/admin/homepage'
    | '/admin/learn'
    | '/admin/media'
    | '/admin/offices'
    | '/admin/programs'
    | '/admin/projects'
    | '/admin/recycle'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/careers/$slug'
    | '/donations/$slug'
    | '/events/$slug'
    | '/news/$slug'
    | '/offices/$slug'
    | '/portal/manager'
    | '/portal/student'
    | '/portal/teacher'
    | '/programs/$slug'
    | '/projects/$slug'
    | '/publications/$slug'
    | '/admin/'
    | '/careers/'
    | '/donations/'
    | '/offices/'
    | '/portal/'
    | '/programs/'
    | '/projects/'
    | '/api/public/hesab-session'
    | '/api/public/prerender-manifest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/learn'
    | '/media'
    | '/admin/about'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/donations'
    | '/admin/homepage'
    | '/admin/learn'
    | '/admin/media'
    | '/admin/offices'
    | '/admin/programs'
    | '/admin/projects'
    | '/admin/recycle'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/careers/$slug'
    | '/donations/$slug'
    | '/events/$slug'
    | '/news/$slug'
    | '/offices/$slug'
    | '/portal/manager'
    | '/portal/student'
    | '/portal/teacher'
    | '/programs/$slug'
    | '/projects/$slug'
    | '/publications/$slug'
    | '/admin'
    | '/careers'
    | '/donations'
    | '/offices'
    | '/portal'
    | '/programs'
    | '/projects'
    | '/api/public/hesab-session'
    | '/api/public/prerender-manifest'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/donate'
    | '/learn'
    | '/media'
    | '/portal'
    | '/admin/about'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/donations'
    | '/admin/homepage'
    | '/admin/learn'
    | '/admin/media'
    | '/admin/offices'
    | '/admin/programs'
    | '/admin/projects'
    | '/admin/recycle'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/careers/$slug'
    | '/donations/$slug'
    | '/events/$slug'
    | '/news/$slug'
    | '/offices/$slug'
    | '/portal/manager'
    | '/portal/student'
    | '/portal/teacher'
    | '/programs/$slug'
    | '/projects/$slug'
    | '/publications/$slug'
    | '/admin/'
    | '/careers/'
    | '/donations/'
    | '/offices/'
    | '/portal/'
    | '/programs/'
    | '/projects/'
    | '/api/public/hesab-session'
    | '/api/public/prerender-manifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  LearnRoute: typeof LearnRoute
  MediaRoute: typeof MediaRoute
  PortalRoute: typeof PortalRouteWithChildren
  CareersSlugRoute: typeof CareersSlugRoute
  DonationsSlugRoute: typeof DonationsSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  OfficesSlugRoute: typeof OfficesSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  PublicationsSlugRoute: typeof PublicationsSlugRoute
  CareersIndexRoute: typeof CareersIndexRoute
  DonationsIndexRoute: typeof DonationsIndexRoute
  OfficesIndexRoute: typeof OfficesIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicHesabSessionRoute: typeof ApiPublicHesabSessionRoute
  ApiPublicPrerenderManifestRoute: typeof ApiPublicPrerenderManifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learn': {
      id: '/admin/learn'
      path: '/learn'
      fullPath: '/admin/learn'
      preLoaderRoute: typeof AdminLearnRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offices': {
      id: '/admin/offices'
      path: '/offices'
      fullPath: '/admin/offices'
      preLoaderRoute: typeof AdminOfficesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recycle': {
      id: '/admin/recycle'
      path: '/recycle'
      fullPath: '/admin/recycle'
      preLoaderRoute: typeof AdminRecycleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations/': {
      id: '/donations/'
      path: '/donations'
      fullPath: '/donations/'
      preLoaderRoute: typeof DonationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations/$slug': {
      id: '/donations/$slug'
      path: '/donations/$slug'
      fullPath: '/donations/$slug'
      preLoaderRoute: typeof DonationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/': {
      id: '/offices/'
      path: '/offices'
      fullPath: '/offices/'
      preLoaderRoute: typeof OfficesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/$slug': {
      id: '/offices/$slug'
      path: '/offices/$slug'
      fullPath: '/offices/$slug'
      preLoaderRoute: typeof OfficesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/manager': {
      id: '/portal/manager'
      path: '/manager'
      fullPath: '/portal/manager'
      preLoaderRoute: typeof PortalManagerRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/student': {
      id: '/portal/student'
      path: '/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof PortalStudentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/teacher': {
      id: '/portal/teacher'
      path: '/teacher'
      fullPath: '/portal/teacher'
      preLoaderRoute: typeof PortalTeacherRouteImport
      parentRoute: typeof PortalRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/$slug': {
      id: '/publications/$slug'
      path: '/publications/$slug'
      fullPath: '/publications/$slug'
      preLoaderRoute: typeof PublicationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hesab-session': {
      id: '/api/public/hesab-session'
      path: '/api/public/hesab-session'
      fullPath: '/api/public/hesab-session'
      preLoaderRoute: typeof ApiPublicHesabSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/prerender-manifest': {
      id: '/api/public/prerender-manifest'
      path: '/api/public/prerender-manifest'
      fullPath: '/api/public/prerender-manifest'
      preLoaderRoute: typeof ApiPublicPrerenderManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLearnRoute: typeof AdminLearnRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOfficesRoute: typeof AdminOfficesRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminRecycleRoute: typeof AdminRecycleRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminContactRoute: AdminContactRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLearnRoute: AdminLearnRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOfficesRoute: AdminOfficesRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminRecycleRoute: AdminRecycleRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalManagerRoute: typeof PortalManagerRoute
  PortalStudentRoute: typeof PortalStudentRoute
  PortalTeacherRoute: typeof PortalTeacherRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalManagerRoute: PortalManagerRoute,
  PortalStudentRoute: PortalStudentRoute,
  PortalTeacherRoute: PortalTeacherRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  LearnRoute: LearnRoute,
  MediaRoute: MediaRoute,
  PortalRoute: PortalRouteWithChildren,
  CareersSlugRoute: CareersSlugRoute,
  DonationsSlugRoute: DonationsSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  OfficesSlugRoute: OfficesSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  PublicationsSlugRoute: PublicationsSlugRoute,
  CareersIndexRoute: CareersIndexRoute,
  DonationsIndexRoute: DonationsIndexRoute,
  OfficesIndexRoute: OfficesIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicHesabSessionRoute: ApiPublicHesabSessionRoute,
  ApiPublicPrerenderManifestRoute: ApiPublicPrerenderManifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
